# Input data
input_w: 128                  
input_h: 128                  
age_min: 20                  
age_max: 70  
# Training hyperparameters                 
batch_size: 16                 
epochs: 25
# Optimizer parameters               
lr: 0.0001         
beta_1: 0.9           
beta_2: 0.999
weight_decay: 0.0005  
# Learning rate scheduler                  
step_size: 10                
gamma: 0.1                                 
# Tensorboard log options
image_save_iter: 250   
image_log_iter: 250       
log_iter: 5                 
# Loss weight
w:
  recon: 10
  class: 3
  adver: 1
  dis: 1
  gp: 1
  tv: 2
